sonar.projectKey=Harshit10bisht_python-bits-aceest-gym
sonar.organization=harshit10bisht
sonar.host.url=https://sonarcloud.io

sonar.projectName=ACEest Fitness
sonar.projectVersion=1.0

sonar.sources=app.py,fitness_core.py
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest-junit.xml
sonar.exclusions=Aceest*.py,tests/**,k8s/**
sonar.coverage.exclusions=tests/**

sonar.sourceEncoding=UTF-8